import type { DocumentRule } from "@/lib/types";

const createdAt = "2026-06-05T05:30:00.000Z";

export const demoRules: DocumentRule[] = [
  {
    id: "rule-limingtun-tail-info",
    name: "黎明屯配送发货单（尾部收货信息）",
    description: "标准 Excel 明细表 + 尾部横向收货人信息，适合头部跳过和标签提取。",
    sourceType: "excel",
    sampleFileName: "12.25海口龙湖天街-配送发货单PS2512220005001(1).xlsx",
    createdAt,
    updatedAt: createdAt,
    confidenceNotes: [
      { field: "externalCode", message: "外部编码取自“单据号”标签。", level: "confirmed" },
      { field: "recipientAddress", message: "收货地址从尾部横向标签区提取。", level: "confirmed" },
    ],
    extractor: {
      kind: "tabular",
      sheetSelector: { mode: "first" },
      headerRow: 4,
      dataStartRow: 5,
      stopConditions: [{ kind: "firstCellEquals", value: "合计" }],
      fieldMappings: [
        { field: "skuCode", source: { kind: "header", header: "物品编码" } },
        { field: "skuName", source: { kind: "header", header: "物品名称" } },
        { field: "skuQty", source: { kind: "header", header: "发货数量" }, transforms: [{ kind: "numberString" }] },
        { field: "skuSpec", source: { kind: "header", header: "规格型号" } },
      ],
      sharedMappings: [
        { field: "externalCode", source: { kind: "label", label: "单据号" } },
        { field: "storeName", source: { kind: "label", label: "收货机构" } },
        { field: "recipientName", source: { kind: "label", label: "收货人" } },
        { field: "recipientPhone", source: { kind: "label", label: "收货电话" } },
        { field: "recipientAddress", source: { kind: "label", label: "收货地址" } },
      ],
      defaults: [{ field: "temperatureZone", value: "常温" }],
    },
  },
  {
    id: "rule-hunan-grouped-lines",
    name: "湖南仓发货明细（跨行聚合）",
    description: "每行含完整收货信息，按配送单号形成同一外部编码的多 SKU 明细。",
    sourceType: "excel",
    sampleFileName: "湖南仓.xlsx",
    createdAt,
    updatedAt: createdAt,
    confidenceNotes: [
      { field: "externalCode", message: "外部编码优先取“配送单号”。", level: "confirmed" },
    ],
    extractor: {
      kind: "tabular",
      sheetSelector: { mode: "first" },
      headerRow: 2,
      dataStartRow: 3,
      rowFilters: [{ kind: "notEmpty", source: { kind: "header", header: "物品编码*" } }],
      fieldMappings: [
        { field: "externalCode", source: { kind: "header", header: "配送单号" } },
        { field: "storeName", source: { kind: "header", header: "收货机构" } },
        { field: "recipientName", source: { kind: "header", header: "收货人" } },
        { field: "recipientPhone", source: { kind: "header", header: "收货电话" } },
        { field: "recipientAddress", source: { kind: "header", header: "收货地址" } },
        { field: "skuCode", source: { kind: "header", header: "物品编码*" } },
        { field: "skuName", source: { kind: "header", header: "物品名称" } },
        { field: "skuQty", source: { kind: "header", header: "发货数量*" }, transforms: [{ kind: "numberString" }] },
        { field: "skuSpec", source: { kind: "header", header: "规格型号" } },
        { field: "remark", source: { kind: "header", header: "单据备注" } },
      ],
      defaults: [{ field: "temperatureZone", value: "常温" }],
    },
  },
  {
    id: "rule-huanlemuchang-matrix",
    name: "欢乐牧场模板（门店矩阵转置）",
    description: "SKU 行 + 门店列的矩阵格式，自动将门店列展开为独立运单行。",
    sourceType: "excel",
    sampleFileName: "欢乐牧场模板0430.xlsx",
    createdAt,
    updatedAt: createdAt,
    confidenceNotes: [
      { field: "storeName", message: "动态门店列会被转成收货门店字段。", level: "confirmed" },
      { field: "externalCode", message: "原文件无明确外部编码，默认留空，建议用户二次确认。", level: "guess" },
    ],
    extractor: {
      kind: "matrixColumns",
      sheetSelector: { mode: "first" },
      headerRow: 1,
      dataStartRow: 2,
      dynamicColumnStart: 14,
      dynamicColumnEnd: 18,
      dynamicStopHeaders: ["下单后结余"],
      dynamicHeaderField: "storeName",
      dynamicValueField: "skuQty",
      dynamicHeaderMappings: [
        { field: "externalCode", source: { kind: "dynamicHeader" } },
        { field: "storeName", source: { kind: "dynamicHeader" } },
      ],
      skipZero: true,
      rowFilters: [{ kind: "notEmpty", source: { kind: "header", header: "SKU名称" } }],
      fixedMappings: [
        { field: "skuCode", source: { kind: "header", header: "外部商品编码", fallbackHeaders: ["SKU条码"] } },
        { field: "skuName", source: { kind: "header", header: "SKU名称" } },
        { field: "skuSpec", source: { kind: "header", header: "规格" } },
      ],
      defaults: [{ field: "temperatureZone", value: "常温" }],
    },
  },
  {
    id: "rule-multi-sheet-store-orders",
    name: "多门店分 Sheet 出库单",
    description: "遍历所有 Sheet，逐个门店解析明细并合并。",
    sourceType: "excel",
    sampleFileName: "多门店分Sheet出库单.xlsx",
    createdAt,
    updatedAt: createdAt,
    confidenceNotes: [
      { field: "storeName", message: "优先提取尾部“收货门店”标签。", level: "confirmed" },
    ],
    extractor: {
      kind: "tabular",
      sheetSelector: { mode: "all" },
      headerRow: 4,
      dataStartRow: 5,
      stopConditions: [{ kind: "emptyRow", minEmptyCells: 6 }],
      rowFilters: [{ kind: "notEmpty", source: { kind: "header", header: "物品编码" } }],
      fieldMappings: [
        { field: "skuCode", source: { kind: "header", header: "物品编码" } },
        { field: "skuName", source: { kind: "header", header: "物品名称" } },
        { field: "skuQty", source: { kind: "header", header: "出库数量" }, transforms: [{ kind: "numberString" }] },
        { field: "skuSpec", source: { kind: "header", header: "规格型号" } },
        { field: "remark", source: { kind: "header", header: "备注" } },
      ],
      sharedMappings: [
        { field: "externalCode", source: { kind: "sheetName" } },
        { field: "storeName", source: { kind: "label", label: "收货门店：" } },
        { field: "recipientName", source: { kind: "label", label: "联系人：" } },
        { field: "recipientPhone", source: { kind: "label", label: "联系电话：" } },
        { field: "recipientAddress", source: { kind: "label", label: "收货地址：" } },
      ],
      defaults: [{ field: "temperatureZone", value: "常温" }],
    },
  },
  {
    id: "rule-card-transfer-orders",
    name: "门店调拨单（卡片式）",
    description: "识别“调拨记录”卡片边界，在每个卡片内提取收货信息和物品小表。",
    sourceType: "excel",
    sampleFileName: "门店调拨单-卡片式.xlsx",
    createdAt,
    updatedAt: createdAt,
    confidenceNotes: [
      { field: "recipientAddress", message: "卡片内地址来自独立标签行。", level: "confirmed" },
    ],
    extractor: {
      kind: "cardBlocks",
      sheetSelector: { mode: "first" },
      blockStartPattern: "^▶\\s*调拨记录",
      metaMappings: [
        {
          field: "externalCode",
          source: { kind: "regex", pattern: "调拨记录\\s*#(\\d+)" },
          transforms: [{ kind: "prepend", value: "CARD-" }],
        },
        { field: "storeName", source: { kind: "label", label: "调入门店" } },
        { field: "recipientName", source: { kind: "label", label: "收货人" } },
        { field: "recipientPhone", source: { kind: "label", label: "电话" } },
        { field: "recipientAddress", source: { kind: "label", label: "收货地址" } },
      ],
      tableHeaderPattern: "物品编码",
      fieldMappings: [
        { field: "skuCode", source: { kind: "header", header: "物品编码" } },
        { field: "skuName", source: { kind: "header", header: "物品名称" } },
        { field: "skuQty", source: { kind: "header", header: "数量" }, transforms: [{ kind: "numberString" }] },
        { field: "skuSpec", source: { kind: "header", header: "规格" } },
      ],
      stopConditions: [{ kind: "emptyRow", minEmptyCells: 4 }],
      defaults: [{ field: "temperatureZone", value: "常温" }],
    },
  },
  {
    id: "rule-qianzhaizhai-pdf",
    name: "黔寨寨 PDF 配送单",
    description: "PDF 文本表格 + 底部签收区信息，适合文本表格规则。",
    sourceType: "pdf",
    sampleFileName: "黔寨寨贵州烙锅（鞍山店）常温.pdf",
    createdAt,
    updatedAt: createdAt,
    confidenceNotes: [
      { field: "recipientName", message: "收货人信息来自末页签收区。", level: "confirmed" },
      { field: "skuSpec", message: "规格型号存在换行，规则会自动拼接续行。", level: "confirmed" },
    ],
    extractor: {
      kind: "textTable",
      tableHeaderPattern: "物品类别\\s+物品编码\\s+物品名称",
      rowStartPattern: "^\\d+\\s+",
      rowPattern:
        "^(?<lineIndex>\\d+)\\s+(?<category>\\S+)\\s+(?<skuCode>[A-Z0-9-]+)\\s+(?<skuName>.+?)\\s+(?<skuSpec>\\S+)\\s+(?<unit>\\S+)\\s+(?<skuQty>\\d+(?:\\.\\d+)?)\\s*(?<remark>.*)$",
      rowPatternFlags: "i",
      continuationMode: "append-to-previous",
      stopPattern: "^合\\s*$|^计\\s+\\d+|^合\\s*计|^制单日期",
      fieldPatterns: [
        { field: "externalCode", pattern: "单据编号[:：]\\s*([^\\s]+)", sectionScope: "document" },
        {
          field: "storeName",
          pattern: "收货机构[:：]\\s*(.+?)\\s+订货机构",
          sectionScope: "document",
        },
        { field: "recipientName", pattern: "收货人[:：]\\s*(\\S+)", sectionScope: "document" },
        { field: "recipientPhone", pattern: "收货电话[:：]\\s*(\\d+)", sectionScope: "document" },
        { field: "recipientAddress", pattern: "收货地址[:：]\\s*(.+)", sectionScope: "document" },
      ],
      defaults: [{ field: "temperatureZone", value: "常温" }],
    },
  },
  {
    id: "template-word-paragraph-records",
    name: "模板：Word 纯文本配送确认单",
    description: "适合无表格、用分隔线拆记录的 Word 文本。",
    sourceType: "word",
    isTemplate: true,
    createdAt,
    updatedAt: createdAt,
    confidenceNotes: [
      { field: "extractor", message: "请根据实际文本分隔线和物品行格式微调正则。", level: "guess" },
    ],
    extractor: {
      kind: "textBlocks",
      blockSplitterPattern: "━{3,}",
      fieldPatterns: [
        { field: "externalCode", pattern: "外部编码[:：]\\s*(.+)" },
        { field: "storeName", pattern: "收货门店[:：]\\s*(.+)" },
        { field: "recipientName", pattern: "收件人[:：]\\s*(.+)" },
        { field: "recipientPhone", pattern: "电话[:：]\\s*(\\d+)" },
        { field: "recipientAddress", pattern: "地址[:：]\\s*(.+)" },
      ],
      itemPattern:
        "(?:^|\\n)\\s*(?:\\d+[.、]\\s*)?(?<skuCode>[A-Z0-9-]+)\\s*\\|\\s*(?<skuName>[^|\\n]+)\\|\\s*(?<skuSpec>[^|\\n]*)\\|\\s*(?<skuQty>\\d+(?:\\.\\d+)?)",
      itemPatternFlags: "gm",
      defaults: [{ field: "temperatureZone", value: "常温" }],
    },
  },
  {
    id: "template-week-plan-matrix",
    name: "模板：周配送计划矩阵",
    description: "适合门店为行、日期为列、单元格内多物品的周计划表。",
    sourceType: "excel",
    isTemplate: true,
    createdAt,
    updatedAt: createdAt,
    confidenceNotes: [
      { field: "remark", message: "动态列头通常会写入备注或作为用户二次确认线索。", level: "guess" },
    ],
    extractor: {
      kind: "matrixColumns",
      sheetSelector: { mode: "first" },
      headerRow: 1,
      dataStartRow: 2,
      dynamicColumnStart: 3,
      dynamicHeaderField: "remark",
      dynamicValueField: "skuQty",
      dynamicHeaderMappings: [
        {
          field: "externalCode",
          source: {
            kind: "template",
            template: "{storeName}-{date}",
            sources: {
              storeName: { kind: "header", header: "门店", fallbackHeaders: ["门店名称"] },
              date: { kind: "dynamicHeader" },
            },
          },
        },
        { field: "remark", source: { kind: "dynamicHeader" } },
      ],
      fixedMappings: [{ field: "storeName", source: { kind: "header", header: "门店", fallbackHeaders: ["门店名称"] } }],
      rowFilters: [{ kind: "notEmpty", source: { kind: "header", header: "门店", fallbackHeaders: ["门店名称"] } }],
      cellItemPattern:
        "(?<skuName>[^xX×*＊\\n]+)[xX×*＊](?<skuQty>\\d+(?:\\.\\d+)?)",
      cellItemFlags: "g",
      cellItemGroupMap: { skuCode: "skuName" },
      defaults: [{ field: "temperatureZone", value: "常温" }],
    },
  },
  {
    id: "template-pdf-multi-order",
    name: "模板：多订单 PDF 签收单",
    description: "适合一个 PDF 内含多个独立订单，每个订单各自有签收信息与物品表格。",
    sourceType: "pdf",
    isTemplate: true,
    createdAt,
    updatedAt: createdAt,
    confidenceNotes: [
      { field: "extractor", message: "如分隔线不固定，可改用 AI 结构化提取。", level: "guess" },
    ],
    extractor: {
      kind: "textTable",
      sectionSplitterPattern: "(?=配送签收单|配送单)",
      fieldPatterns: [
        { field: "externalCode", pattern: "单据编号[:：]\\s*(\\S+)", sectionScope: "section" },
        { field: "storeName", pattern: "收货机构[:：]\\s*(.+)", sectionScope: "section" },
        { field: "recipientName", pattern: "收货人[:：]\\s*(\\S+)", sectionScope: "section" },
        { field: "recipientPhone", pattern: "收货电话[:：]\\s*(\\d+)", sectionScope: "section" },
        { field: "recipientAddress", pattern: "收货地址[:：]\\s*(.+)", sectionScope: "section" },
      ],
      tableHeaderPattern: "物品编码\\s+物品名称",
      rowStartPattern: "^\\d+\\s+",
      rowPattern:
        "^(?<lineIndex>\\d+)\\s+(?<skuCode>[A-Z0-9-]+)\\s+(?<skuName>.+?)\\s+(?<skuSpec>\\S+)\\s+(?<skuQty>\\d+(?:\\.\\d+)?)\\s*(?<remark>.*)$",
      continuationMode: "append-to-previous",
      stopPattern: "^合\\s*$|^计\\s+\\d+|^合\\s*计|^签字|^备注",
      defaults: [{ field: "temperatureZone", value: "常温" }],
    },
  },
];
