import { Client, Receiver } from "@upstash/qstash";
import type { ImportQueueEvent } from "@/lib/async-import-types";
import { addTrace, listOutbox, markOutboxFailed, markOutboxSent } from "@/lib/server/async-import-storage";

export function queueConfigured(){return Boolean(process.env.QSTASH_TOKEN&&process.env.QSTASH_CURRENT_SIGNING_KEY&&process.env.QSTASH_NEXT_SIGNING_KEY)}

export async function dispatchOutbox(origin:string,limit=50){const events=await listOutbox(limit);let sent=0;let failed=0;if(!process.env.QSTASH_TOKEN)return{sent,failed:events.length,pending:events.length,available:false};const client=new Client({token:process.env.QSTASH_TOKEN});for(const record of events){const envelope=record.payload as ImportQueueEvent;const isBatch=envelope.event_type==="ImportBatchCreated";const unitId=isBatch?envelope.payload.unit_id:undefined;try{await client.publishJSON({url:`${origin}${isBatch?"/api/import-workers/batch":"/api/import-workers/parse"}`,body:envelope,retries:3,flowControl:{key:isBatch?"import-batches":"import-parsers",parallelism:isBatch?4:2,ratePerSecond:isBatch?10:2}});await markOutboxSent(String(record.id));await addTrace({traceId:envelope.trace_id,taskId:envelope.aggregate_id,unitId,eventName:isBatch?"ImportBatchQueued":"ImportFileQueued",status:"info",message:isBatch?`处理单元 ${unitId} 已进入队列`:"文件解析任务已进入队列",metadata:{eventId:envelope.event_id}});sent+=1;}catch(error){failed+=1;await markOutboxFailed(String(record.id),error instanceof Error?error.message:"QStash 投递失败");}}return{sent,failed,pending:Math.max(0,events.length-sent),available:true}}

export async function verifyQueueRequest(request:Request,body:string){if(process.env.NODE_ENV!=="production"&&process.env.ALLOW_UNSIGNED_WORKER==="true")return true;const currentSigningKey=process.env.QSTASH_CURRENT_SIGNING_KEY;const nextSigningKey=process.env.QSTASH_NEXT_SIGNING_KEY;if(!currentSigningKey||!nextSigningKey)return false;const signature=request.headers.get("upstash-signature");if(!signature)return false;const receiver=new Receiver({currentSigningKey,nextSigningKey});return receiver.verify({signature,body,url:request.url});}
